name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Display .NET version
        run: dotnet --version

      - name: Set VERSION variable from tag
        run: echo "VERSION=0.0.0" >> $GITHUB_ENV

      - name: Download References
        shell: pwsh
        run: |
          .\Download-References.ps1

      - name: Build DLLs - Oxide
        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Oxide /p:Version=$VERSION /p:BuildServer=Github -f net48
        working-directory: Oxide.Ext.Discord

      - name: Build DLLs - Carbon
        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Carbon /p:Version=$VERSION /p:BuildServer=Github -f net48
        working-directory: Oxide.Ext.Discord
